name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease
        ls -la app/build/outputs/apk/release/
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: YemeniLawyer-APK
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 7
